[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  noremap <silent><C-e> :NERDTreeTabsToggle<CR>
  autocmd bufenter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | q | endif

  let g:NERDTreeShowHidden = 1
  if winwidth(0) < 128
    let g:NERDTreeWinSize = 25
  endif
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
