[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  nnoremap <silent> ,uy :<C-u>Unite history/yank<CR>
  nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
  nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
  nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
  nnoremap <silent> ,uu :<C-u>Unite file_mru buffer<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  "Ctrl+Kにターゲットジャンプ割当
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# Rubyの自動補完
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

# Rubyのend補完
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

# Rubyのメソッドの定義元にジャンプ
[[plugins]]
repo = 'szw/vim-tags'

# PHP vdebug
[[plugins]]
repo = 'joonty/vdebug'
on_ft = ['php']

# PHP 補完
[[plugins]]
repo = 'padawan-php/deoplete-padawan'
on_ft = ['php']

# Go 
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

# rust-vim
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_source = '''
  let g:deoplete#sources#rust#racer_binary='{$HOME/.cargo/bin/racer}'
  let g:deoplete#sources#rust#rust_source_path='{$(rustc --print sysroot)/lib/rustlib/src/rust/src}'
  let g:deoplete#sources#rust#show_duplicates=1
  let g:deoplete#sources#rust#disable_keymap=1
  nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
  nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
  " racerバイナリ指定
  let g:racer_cmd = "~/.cargo/bin/racer"
'''

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'Dockerfile'
